// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var directiveScopeReadyLimit = 10;
var directiveScopeReadyTimeout = 200;
window.onbeforeunload = (e) => {
    if (window._context.isDirty) {
        var msg = window._resourcesManager.getGlobalResource("RES_WEBFORM_DirtyMessage");
        e.returnValue = msg;     // Gecko, Trident, Chrome 34+
        return msg;
    }
};
interface Window { scope_PermissionsList: DSS1_RetailerDriverStockOptimisation.Controllers.IPermissionsListScope; }
namespace DSS1_RetailerDriverStockOptimisation.Controllers {
const PermissionsListConditionalFormattings = [
        ];
const PermissionsListDataValidations = [
                                       ];
const PermissionsListCalculatedExpressions = [
        ];

// Datasets Column Info
export var List1DataSet_ColumnInfo = [new Joove.ColumnInfo("Name", "string", null, false),
                                      new Joove.ColumnInfo("Description", "string", null, false)];
window["List1DataSet_ColumnInfo"] = List1DataSet_ColumnInfo;

// Datasets Projection Shemas
window["Table_ProjectionScema"] = {};


export interface IPermissionsListScope extends Joove.IWebPageScope {
model:
    DSS1_RetailerDriverStockOptimisation.ViewModels.PermissionsList.PermissionsListViewModel;
_partialModelStructure:
    any;
    _validations?: {
summary: Array<Joove.Validation.BindingEntry>,

    },
    _masterValidations?: any;
}

class PermissionsListController {
private timeoutDelayLockIcon11Clicked:
    any;
private timeoutDelayLockButton2Clicked:
    any;
private timeoutDelayLockNameClicked:
    any;
private timeoutDelayLockMailClicked:
    any;
private timeoutDelayLockRowControl1OnDoubleClick:
    any;
private timeoutDelayLockIcon3Clicked:
    any;


    private controllerActionFinished = (resetDirty: boolean) => {
        //window.scope_PermissionsList.model = window.scope_PermissionsList.dehydrate();
        //window.scope_MasterPage.model = window.scope_PermissionsList.model;
        DSS1_RetailerDriverStockOptimisation.ViewModels.PermissionsList.PermissionsListViewModel._lightCast(window.scope_PermissionsList.model);
        // Joove.Common.applyScope(window.scope_PermissionsList);
        if (resetDirty) {
            window._context.isDirty = false;
        }
        window._ruleEngine.update(Joove.EvaluationTimes.OnChange);
    }

    constructor(private $scope: IPermissionsListScope, $timeout: ng.ITimeoutService) {
        window.scope_PermissionsList = $scope;
        $scope.$onControlChanged = function (event, newValue, dontMakeDirty) {
            Joove.Core.onChange(event.target, newValue, dontMakeDirty)
        }

        $scope.dehydrate = (context = null) => DSS1_RetailerDriverStockOptimisation.ViewModels.PermissionsList.PermissionsListViewModel._initializeFrom($scope.model, context);
        $scope._validationsMaster =  window.scope_MasterPage._validations;
        $scope._validations = { summary:
                                [],
                              };

        this.init($scope, $timeout);
        $timeout(() => {

            window._ruleEngine.update(Joove.EvaluationTimes.OnLoad, null, () => {

                $("body").fadeIn(200);

            });
        });

    }

    init($scope: IPermissionsListScope, $timeout: ng.ITimeoutService) {


        $scope.model = DSS1_RetailerDriverStockOptimisation.ViewModels.PermissionsList.PermissionsListViewModel._initializeFrom(window.viewDTO.Model);

        window.scope_MasterPage.model = $scope.model;

        new Joove.ReferencesReconstructor().reconstructReferences($scope.model);
        $scope.trackObject = obj => Joove.Common.trackObject(obj);


        //}

        $.connection['eventsHub'].on('__connectedEvent');

        $.connection['eventsHub'].on('forcePageReload', () => {
            window.onbeforeunload = null;
            setTimeout(() => {
                window.location.reload();
            }, 3000);
        });
        $.connection.hub.start(() => {
            Joove.Common.getScope().connectedToSignals();
            Joove.Common.getMasterScope().connectedToSignals();

        });
        $scope.connectedToSignals = () => {
        }
// Event Listeners
        $scope.events = {
        };
        $scope.expressions = {
        }
// Dataset Handler
        $scope.datasets = {
        };
// Controller actions
        $scope.actions = {
Refresh:
            async (_cb, _modalOptions, _e) => {
                Joove.Common.autocompleteFix();

                const implementation = async (): Promise<any> => {
                    Joove.Common.nullSafe<any>(() => window._commander.gridRefresh(["Table"]), null);


                    // Joove.Common.applyScope(window.scope_PermissionsList);
                }

                await window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit);

                let spamHelper = new Joove.SpamControlHelper(_e);
                spamHelper.Disable();
                await implementation();
                spamHelper.Enable();
                this.controllerActionFinished(true);
            },
Retrieve:
            async (_cb, _modalOptions, _e) => {
                Joove.Common.autocompleteFix();


                Joove.Core.executeRedirectControllerAction("PermissionsList", "Retrieve", "GET", [], {}, _modalOptions);
            },
        };
// Events
        $scope.eventCallbacks = {
Icon11Clicked:
            (e: any): any => {
                window._recorder.addState(e);

                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                Joove.DatasourceManager.clearFiltersToControlsBoundToDataSet('List1DataSet', e);
            },

Button2Clicked:
            (e, DataItem, _parents) => {
                window._recorder.addState(e);

                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                if (this.timeoutDelayLockButton2Clicked != null) {
                    $timeout.cancel(this.timeoutDelayLockButton2Clicked);
                }

                this.timeoutDelayLockButton2Clicked = $timeout(() => {
                    Joove.Common.setControlKeyPressed(e, 0); Joove.Common.setLastClickedElement(e);

                    Joove.Validation.Manager.validateFormAndExecute(() => {
                        //This is true only when the menu item is clicked programmatically
                        //and occurs when the middle mouse button click is triggered
                        var openInNewWindow = $(e.target).data("openInNewWindow") === true || undefined;
if (openInNewWindow) $(e.target).data("openInNewWindow", undefined); Joove.Core.executeRedirectControllerAction("ManagePermission", "NewPermission", "GET", [], {}, { mode: 'Slide', width: '50%', height: '50%', onClose: () => { $scope.actions.Refresh(); }});
}, { groups: [], withDataValidationsCheck: false, withRequiredFieldsCheck: false });
                }, 0);
            },

NameClicked:
            (e: any): any => {
                window._recorder.addState(e);

                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                var $element = $(e.target);
                var targetProp = $element.attr('joove-ds-sort-OnClick');

                Joove.DatasourceManager.sortControlsBoundToDataSet('List1DataSet', targetProp, e);
            },

MailClicked:
            (e: any): any => {
                window._recorder.addState(e);

                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                var $element = $(e.target);
                var targetProp = $element.attr('joove-ds-sort-OnClick');

                Joove.DatasourceManager.sortControlsBoundToDataSet('List1DataSet', targetProp, e);
            },

RowControl1OnDoubleClick:
            (e, DataItem, _parents) => {
                window._recorder.addState(e);

                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                if (this.timeoutDelayLockRowControl1OnDoubleClick != null) {
                    $timeout.cancel(this.timeoutDelayLockRowControl1OnDoubleClick);
                }

                this.timeoutDelayLockRowControl1OnDoubleClick = $timeout(() => {
                    Joove.Common.setControlKeyPressed(e, 0); Joove.Common.setLastClickedElement(e);

                    Joove.Validation.Manager.validateFormAndExecute(() => {
                        //This is true only when the menu item is clicked programmatically
                        //and occurs when the middle mouse button click is triggered
                        var openInNewWindow = $(e.target).data("openInNewWindow") === true || undefined;
if (openInNewWindow) $(e.target).data("openInNewWindow", undefined); Joove.Core.executeRedirectControllerAction("ManagePermission", "EditPermission", "GET", [Joove.Common.nullSafe<any>(() => _parents[0].Id, 0)], {}, { mode: 'Slide', width: '50%', height: '50%', onClose: () => { $scope.actions.Refresh(); }});
}, { groups: [], withDataValidationsCheck: false, withRequiredFieldsCheck: false });
                }, 0);
            },

Icon3Clicked:
            (e, DataItem, _parents) => {
                window._recorder.addState(e);

                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                if (this.timeoutDelayLockIcon3Clicked != null) {
                    $timeout.cancel(this.timeoutDelayLockIcon3Clicked);
                }

                this.timeoutDelayLockIcon3Clicked = $timeout(() => {
                    Joove.Common.setControlKeyPressed(e, 0); Joove.Common.setLastClickedElement(e);

                    Joove.Validation.Manager.validateFormAndExecute(() => {
                        //This is true only when the menu item is clicked programmatically
                        //and occurs when the middle mouse button click is triggered
                        var openInNewWindow = $(e.target).data("openInNewWindow") === true || undefined;
if (openInNewWindow) $(e.target).data("openInNewWindow", undefined); Joove.Core.executeRedirectControllerAction("ManagePermission", "EditPermission", "GET", [Joove.Common.nullSafe<any>(() => _parents[0].Id, 0)], {}, { mode: 'Slide', width: '50%', height: '50%', onClose: () => { $scope.actions.Refresh(); }});
}, { groups: [], withDataValidationsCheck: false, withRequiredFieldsCheck: false });
                }, 0);
            },

        };

// Rules
        window._ruleEngine.addDataValidations(PermissionsListDataValidations);
        window._ruleEngine.addConditionalFormattings(PermissionsListConditionalFormattings);
        window._ruleEngine.addCalculatedExpressions(PermissionsListCalculatedExpressions);

        window._commander.executeCommands(window.viewDTO.ClientCommands);
        window.viewDTO.ClientCommands = [];

        Joove.Common.setNumberLocalizationSettings();
        Joove.DeveloperApi.init($scope as any, window.scope_MasterPage as any);
        window.$formExtend && window.$formExtend();
        window.$onFormLoaded && window.$onFormLoaded();
    }
}
angular.module("Application").controller("PermissionsListController", ["$scope", "$timeout", PermissionsListController] as Array<string>);
}
