
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;

using DSS1_RetailerDriverStockOptimisation.DAL;

namespace DSS1_RetailerDriverStockOptimisation.BO
{
	/// <summary>
	/// The AppNotification extensions
	/// </summary>
	public static class AppNotificationExtensions
	{
        public static void CreateAppNotification(string itemSKU, int? delta, string recipientUsername, DSS1_RetailerDriverStockOptimisation.BO.OrderForecastDetails ofDetail){using (new zAppDev.DotNet.Framework.Profiling.Profiler("AppNotification", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "CreateAppNotification")) {
DSS1_RetailerDriverStockOptimisation.BO.Contact recipient = new DSS1_RetailerDriverStockOptimisation.BO.Contact();
try {
recipient =  new DSS1_RetailerDriverStockOptimisation.DAL.Repository().GetById<DSS1_RetailerDriverStockOptimisation.BO.Contact>(recipientUsername);}
catch (System.Exception x) {
zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Error, "AppNotification",  DSS1_RetailerDriverStockOptimisation.Hubs.EventsHub.RaiseDebugMessage, x);
return;
}
DSS1_RetailerDriverStockOptimisation.BO.AppNotification appNotification = new DSS1_RetailerDriverStockOptimisation.BO.AppNotification();
appNotification.Recipient = recipient;appNotification.Item = itemSKU;appNotification.Delta = delta;appNotification.IsRead = false;appNotification.DateCreated = DateTime.UtcNow;DSS1_RetailerDriverStockOptimisation.BO.AppNotificationAction appNotificationAction = new DSS1_RetailerDriverStockOptimisation.BO.AppNotificationAction();
appNotification?.AddAppNotificationActions(appNotificationAction);
new DSS1_RetailerDriverStockOptimisation.DAL.Repository().Save<DSS1_RetailerDriverStockOptimisation.BO.AppNotification>(appNotification);
DSS1_RetailerDriverStockOptimisation.Hubs.EventsHub.RaiseAppNotificationCreated();
}
}



        
	}
}
