
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;

using DSS1_RetailerDriverStockOptimisation.DAL;

namespace DSS1_RetailerDriverStockOptimisation.BO
{
	/// <summary>
	/// The Convertor extensions
	/// </summary>
	public static class ConvertorExtensions
	{
        public static System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.Buckets> ToBucket(DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.Bucket[] items){using (new zAppDev.DotNet.Framework.Profiling.Profiler("Convertor", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "ToBucket")) {
System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.Buckets> buckets = new System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.Buckets>();
foreach (var bucket in items ?? Enumerable.Empty<DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.Bucket>()) {
buckets?.Add((new DSS1_RetailerDriverStockOptimisation.BO.ElasticsearchDataTransformation.Transformer()).ELKBucket_To_Bucket(bucket));
}
return buckets;
}
}


public static System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.RequestLog> ToRequestLog(DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.SearchResponse queryResponse){using (new zAppDev.DotNet.Framework.Profiling.Profiler("Convertor", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "ToRequestLog")) {
System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.RequestLog> logs = new System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.RequestLog>();
foreach (var hit in queryResponse.HitResponce.Hits ?? Enumerable.Empty<DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.HitRoot>()) {
logs?.Add((new DSS1_RetailerDriverStockOptimisation.BO.ElasticsearchDataTransformation.Transformer()).Hit_To_RequestLog(hit.Source));
}
return logs;
}
}


public static System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket> ToDateHistBucket(System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.HistogramBucket> items){using (new zAppDev.DotNet.Framework.Profiling.Profiler("Convertor", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "ToDateHistBucket")) {
DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket tmp = new DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket();
System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket> buckets = new System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket>();
foreach (var bucket in items ?? Enumerable.Empty<DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.HistogramBucket>()) {
tmp = (new DSS1_RetailerDriverStockOptimisation.BO.ElasticsearchDataTransformation.Transformer()).HistogramBucket_To_HIstogramBucket(bucket);tmp.max = bucket.Statistics.max;tmp.min = bucket.Statistics.min;tmp.avg = bucket.Statistics.avg;tmp.sum = bucket.Statistics.sum;tmp.failure = bucket.Errors.Buckets.Failure.doc_count;tmp.success = bucket.Errors.Buckets.Success.doc_count;if ((tmp?.doc_count == 0)) {
tmp.error_rate = zAppDev.DotNet.Framework.Utilities.Common.SafeCast<float?>((0));}
else {
tmp.error_rate = (zAppDev.DotNet.Framework.Utilities.Common.SafeCast<float?>((tmp?.failure ?? 0))) / (zAppDev.DotNet.Framework.Utilities.Common.SafeCast<float?>((tmp?.doc_count ?? 0))) * 100;}
buckets?.Add(tmp);
}
return buckets;
}
}


public static System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket> ToHistBucket(System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.HistogramBucket> items){using (new zAppDev.DotNet.Framework.Profiling.Profiler("Convertor", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "ToHistBucket")) {
System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket> buckets = new System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.HIstogramBucket>();
foreach (var bucket in items ?? Enumerable.Empty<DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.HistogramBucket>()) {
buckets?.Add((new DSS1_RetailerDriverStockOptimisation.BO.ElasticsearchDataTransformation.Transformer()).HistogramBucket_To_HIstogramBucket_2(bucket));
}
return buckets;
}
}


public static System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.Buckets> ErrorRateToBucket(DSS1_RetailerDriverStockOptimisation.ExternalStructs.Elasticsearch.ErrorFilterAggResponse error){using (new zAppDev.DotNet.Framework.Profiling.Profiler("Convertor", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "ErrorRateToBucket")) {
DSS1_RetailerDriverStockOptimisation.BO.Buckets fail = new DSS1_RetailerDriverStockOptimisation.BO.Buckets();
fail.key = "Failure";fail.doc_count = error.Buckets.Failure.doc_count;DSS1_RetailerDriverStockOptimisation.BO.Buckets success = new DSS1_RetailerDriverStockOptimisation.BO.Buckets();
success.key = "Success";success.doc_count = error.Buckets.Success.doc_count;System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.Buckets> buckets = new System.Collections.Generic.List<DSS1_RetailerDriverStockOptimisation.BO.Buckets>();
buckets?.Add(fail);
buckets?.Add(success);
return buckets;
}
}



        
	}
}
