// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS1_RetailerDriverStockOptimisation.BO;
using DSS1_RetailerDriverStockOptimisation.BoTesting.Tests.Common;
using DSS1_RetailerDriverStockOptimisation.DAL;

namespace DSS1_RetailerDriverStockOptimisation.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for NotificationTest and is intended
    ///to contain all NotificationTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("Notification Repository Tests")]
    [Category("Notification Repository Tests")]
    internal class NotificationTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `Notification`")]
        [Order(0)]
        public void Notification_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _notification_item_notifications = new DSS1_RetailerDriverStockOptimisation.BO.Item
            {
                SKU = "8a430ffc-1da7-4374-ad34-4d3f1a331aeaItem_SKU",
                Description = "Item_Description",
                UPC = "Item_UPC",
                AvgDailyDemand = 222222.22M,
                PalletSize = 7256,
                SupplierPackSize = 5965,
                InnerPackSize = 7979,
                PalletType = "Item_PalletType",
                PalTI = 3577,
                PalHI = 998,
                UOM = "Item_UOM",
            };
            var _notification_warehouse_notification = new DSS1_RetailerDriverStockOptimisation.BO.Warehouse
            {
                Code = "Warehouse_Code",
                Description = "Warehouse_Description",
                FlowType = "Warehouse_FlowType",
            };
            var _orderproposal_orderforecastdetails_notification = new DSS1_RetailerDriverStockOptimisation.BO.OrderForecastDetails
            {
                ReplenishmentCycle = 5236,
                AutomatedForecast = 349,
                Quantity = 2222222222.22222M,
                RoundQuantity = 6891,
                OrderInventoryDays = 2222222222.22222M,
                RecommendedOrderDate = now,
                SalesForecastDate = now,
                SupplierCanDeliver = true,
                SupplierMaxQuantity = 2222222222.22222M,
                SupplierCoverageDays = 3753,
                ItemCoverageDays = 9727,
                InitialStockLevel = 6612,
                SupplierAvailableQuantity = 484,
                SupplierSharesStock = true,
                CreatedOn = now,
                Status = "OrderForecastDetails_Status",
            };
            new PersistenceSpecification<DSS1_RetailerDriverStockOptimisation.BO.Notification>(Session)
            .CheckProperty(p => p.Message, "Notification_Message")
            .CheckProperty(p => p.TotalSupplierStock, 9421)
            .CheckProperty(p => p.OrderForecastQuantity, 7030)
            .CheckProperty(p => p.Diff, 1721)
            .CheckProperty(p => p.SalesForecastDate, now)
            .CheckProperty(p => p.CreatedBy, "Notification_CreatedBy")
            .CheckReference(p => p.Item, _notification_item_notifications)
            .CheckReference(p => p.Warehouse, _notification_warehouse_notification)
            .CheckReference(p => p.OrderForecastDetails, _orderproposal_orderforecastdetails_notification)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `Notification`")]
        [Order(1)]
        public void Notification_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS1_RetailerDriverStockOptimisation.BO.Notification> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS1_RetailerDriverStockOptimisation.BO.Notification>(
                              a => true
                              && (a.Message != string.Empty && a.Message != null)
                              && (a.TotalSupplierStock + 123 > 0)
                              && (a.OrderForecastQuantity + 123 > 0)
                              && (a.Diff + 123 > 0)
                              && a.SalesForecastDate.GetValueOrDefault().Date <= DateTime.UtcNow.Date
                              && (a.CreatedBy != string.Empty && a.CreatedBy != null)
                              && a.Item != null
                              && a.Warehouse != null
                              && a.OrderForecastDetails != null
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}