// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS1_RetailerDriverStockOptimisation;
(function (DSS1_RetailerDriverStockOptimisation) {
    var Services;
    (function (Services) {
        /**
         * Client for 'capacities' Service
         */
        var capacitiesServiceClient = /** @class */ (function () {
            function capacitiesServiceClient() {
            }
            /**
            *
            */
            capacitiesServiceClient.Publish = function (capacities) {
                var _data = capacities;
                return axios.post(window._context.siteRoot + capacitiesServiceClient.baseUrl + "Publish", _data);
            };
            /**
             * Base url for 'capacities' Service
             */
            capacitiesServiceClient.baseUrl = "/api/capacities/";
            return capacitiesServiceClient;
        }());
        Services.capacitiesServiceClient = capacitiesServiceClient;
    })(Services = DSS1_RetailerDriverStockOptimisation.Services || (DSS1_RetailerDriverStockOptimisation.Services = {}));
})(DSS1_RetailerDriverStockOptimisation || (DSS1_RetailerDriverStockOptimisation = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.capacities = DSS1_RetailerDriverStockOptimisation.Services.capacitiesServiceClient;
