// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS1_RetailerDriverStockOptimisation;
(function (DSS1_RetailerDriverStockOptimisation) {
    var Services;
    (function (Services) {
        /**
         * Client for 'exportSalesForecastDetails' Service
         */
        var exportSalesForecastDetailsServiceClient = /** @class */ (function () {
            function exportSalesForecastDetailsServiceClient() {
            }
            /**
            *
            */
            exportSalesForecastDetailsServiceClient.ExportSalesForecastDetails = function () {
                var _data = { params: {} };
                return axios.get(window._context.siteRoot + exportSalesForecastDetailsServiceClient.baseUrl + "Export", _data);
            };
            /**
             * Base url for 'exportSalesForecastDetails' Service
             */
            exportSalesForecastDetailsServiceClient.baseUrl = "/api/exportSalesForecastDetails/";
            return exportSalesForecastDetailsServiceClient;
        }());
        Services.exportSalesForecastDetailsServiceClient = exportSalesForecastDetailsServiceClient;
    })(Services = DSS1_RetailerDriverStockOptimisation.Services || (DSS1_RetailerDriverStockOptimisation.Services = {}));
})(DSS1_RetailerDriverStockOptimisation || (DSS1_RetailerDriverStockOptimisation = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.exportSalesForecastDetails = DSS1_RetailerDriverStockOptimisation.Services.exportSalesForecastDetailsServiceClient;
