// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS1_RetailerDriverStockOptimisation;
(function (DSS1_RetailerDriverStockOptimisation) {
    var Services;
    (function (Services) {
        /**
         * Client for 'inventoryItems' Service
         */
        var inventoryItemsServiceClient = /** @class */ (function () {
            function inventoryItemsServiceClient() {
            }
            /**
            * Import Inventory Items
            */
            inventoryItemsServiceClient.Import = function (inventoryItems) {
                var _data = inventoryItems;
                return axios.post(window._context.siteRoot + inventoryItemsServiceClient.baseUrl + "import", _data);
            };
            /**
             * Base url for 'inventoryItems' Service
             */
            inventoryItemsServiceClient.baseUrl = "/api/inventoryItems/";
            return inventoryItemsServiceClient;
        }());
        Services.inventoryItemsServiceClient = inventoryItemsServiceClient;
    })(Services = DSS1_RetailerDriverStockOptimisation.Services || (DSS1_RetailerDriverStockOptimisation.Services = {}));
})(DSS1_RetailerDriverStockOptimisation || (DSS1_RetailerDriverStockOptimisation = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.inventoryItems = DSS1_RetailerDriverStockOptimisation.Services.inventoryItemsServiceClient;
