// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS1_RetailerDriverStockOptimisation;
(function (DSS1_RetailerDriverStockOptimisation) {
    var Services;
    (function (Services) {
        /**
         * Client for 'salesForecasts' Service
         */
        var salesForecastsServiceClient = /** @class */ (function () {
            function salesForecastsServiceClient() {
            }
            /**
            * Import Sales Forecasts
            */
            salesForecastsServiceClient.Import = function (salesForecasts) {
                var _data = salesForecasts;
                return axios.post(window._context.siteRoot + salesForecastsServiceClient.baseUrl + "import", _data);
            };
            /**
             * Base url for 'salesForecasts' Service
             */
            salesForecastsServiceClient.baseUrl = "/api/salesForecasts/";
            return salesForecastsServiceClient;
        }());
        Services.salesForecastsServiceClient = salesForecastsServiceClient;
    })(Services = DSS1_RetailerDriverStockOptimisation.Services || (DSS1_RetailerDriverStockOptimisation.Services = {}));
})(DSS1_RetailerDriverStockOptimisation || (DSS1_RetailerDriverStockOptimisation = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.salesForecasts = DSS1_RetailerDriverStockOptimisation.Services.salesForecastsServiceClient;
