// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS1_RetailerDriverStockOptimisation;
(function (DSS1_RetailerDriverStockOptimisation) {
    var Services;
    (function (Services) {
        /**
         * Client for 'stocksOnHand' Service
         */
        var stocksOnHandServiceClient = /** @class */ (function () {
            function stocksOnHandServiceClient() {
            }
            /**
            * Import Stock on Hand
            */
            stocksOnHandServiceClient.Import = function (stocks) {
                var _data = stocks;
                return axios.post(window._context.siteRoot + stocksOnHandServiceClient.baseUrl + "import", _data);
            };
            /**
             * Base url for 'stocksOnHand' Service
             */
            stocksOnHandServiceClient.baseUrl = "/api/stocksOnHand/";
            return stocksOnHandServiceClient;
        }());
        Services.stocksOnHandServiceClient = stocksOnHandServiceClient;
    })(Services = DSS1_RetailerDriverStockOptimisation.Services || (DSS1_RetailerDriverStockOptimisation.Services = {}));
})(DSS1_RetailerDriverStockOptimisation || (DSS1_RetailerDriverStockOptimisation = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.stocksOnHand = DSS1_RetailerDriverStockOptimisation.Services.stocksOnHandServiceClient;
